### ISSUE TITLE
wrapped-styles.js is missing

### ISSUE THREAD

**Issue by Kiho** [svelte-toolbox/svelte-toolbox#21]
Show error on build.
```
src/components/components.module.js → dist/index.min.mjs, dist/index.min.js...
[!] Error: Could not resolve '../styles/internal/wrapped-styles.js' from src\components\Style.svelte
Error: Could not resolve '../styles/internal/wrapped-styles.js' from src\components\Style.svelte
    at error (D:\work\svelte3\svelte-toolbox\node_modules\rollup\dist\rollup.js:9365:30)
    at ModuleLoader.handleMissingImports (D:\work\svelte3\svelte-toolbox\node_modules\rollup\dist\rollup.js:16317:17)
    at ModuleLoader.<anonymous> (D:\work\svelte3\svelte-toolbox\node_modules\rollup\dist\rollup.js:16368:26)
    at Generator.next (<anonymous>)
    at fulfilled (D:\work\svelte3\svelte-toolbox\node_modules\rollup\dist\rollup.js:15368:28)
```

**Comment by Vehmloewff** [comment]
Thanks for the issue @Kiho !

Did this error come up on `npm run build` or `npm run dev`?

It appears that this might happen if `npm run build` is executed before `npm run dev`.

If this is the case, you can `npm run dev`, then `npm run build`.

I will try to fix this issue ASAP.

Thanks again!

**Comment by Kiho** [comment]
Hi @Vehmloewff file is not existing in the place, might be excluded in git.
https://github.com/svelte-toolbox/svelte-toolbox/tree/master/src/styles/internal

**Comment by Vehmloewff** [comment]
Because it is generated from [`styles.scss`](https://github.com/svelte-toolbox/svelte-toolbox/blob/master/src/styles/mdc.scss), it is in the [`.gitignore`](https://github.com/svelte-toolbox/svelte-toolbox/blob/master/.gitignore#L7).  Currently `npm run dev` creates the file, but `npm run build` doesn't.  #22 should fix that.

**Comment by Vehmloewff** [comment]
Now that #22 is merged, when I release the next version this should be fixed, so I think I will go ahead and close this issue for now.

Thanks again @Kiho!
