### ISSUE TITLE
hideOverflow does not work

### ISSUE THREAD

**Issue by Gninoskcaj** [svelte-toolbox/svelte-toolbox#28]
`hideOverflow="false"` does not work.

```html
<script>
	import { Ripple } from 'svelte-toolbox'
</script>

<Ripple hideOverflow="false">
	<p>
		text
	</p>
</Ripple>

```

Demo [here](https://svelte.dev/repl/bd5306032d684736a58c6f175d80c411?version=3.6.6)

**Comment by Vehmloewff** [comment]
That is because you are setting the prop `hideOverflow` to the _string_ `'true'`.

This should work:
```html
<Ripple hideOverflow={false}/>
```

[Demo](https://svelte.dev/repl/6a20fc216fb84138a1a0691e5d937785?version=3.6.7)

**Comment by Vehmloewff** [comment]
You might be interested in https://github.com/sveltejs/svelte/issues/2935
